package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/reposComputoDistribuido/Corba/CorbaFiboInterface/CorbaFiboInterface/src/fibonacci.idl
* miércoles 21 de julio de 2021 01:00:34 AM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
